apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wrqkt6bpp-python 
  janus-idp.io/tekton: wrqkt6bpp-python
  backstage.io/kubernetes-id: wrqkt6bpp-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wrqkt6bpp-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml