apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wrqkt6bpp-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wrqkt6bpp-python 
  name: wrqkt6bpp-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wrqkt6bpp-python 
